services:
  app:
    build:
      context: .
    volumes:
      - .:/workspace
      - /workspace/node_modules
    depends_on:
      - db
    env_file: .env
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: pronity
      PGHOST: db
      PGPORT: 5432
      DATABASE_URL: postgres://postgres:postgres@db:5432/pronity
      BACKEND_PORT: 8000
    ports:
      - "8000:8000"
    command: [ "sh", "-c", "./entrypoint.sh" ]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pronity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
